name: Reusable Deploy workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    - name: Example
      run: |-
        echo "Example Reusable Workflow: $ENVIRONMENT"
    
    env:
      USERNAME: ${{ inputs.username }}